# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, help_text='문재인당선', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='최대 100자 내외', max_length=100),
        ),
    ]
